# Generated by Django 5.0.2 on 2024-02-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
